"""Phase 2 security tests (generated).

Header parity, CORS, auth bypass, injection, traversal, method
restrictions and encoded payloads; see tests/tools/phase2_generator.py."""

# multilingual fixtures use non-ASCII on purpose
from __future__ import annotations

from typing import Any

import pytest

from tests.base_test import BaseTest

_METHOD_RESTRICTION_CASES: tuple[tuple[str, str, int, int], ...] = (
    (
        "POST",
        "/moderate",
        200,
        9102,
    ),
    (
        "GET",
        "/moderate",
        405,
        9103,
    ),
    (
        "PUT",
        "/moderate",
        405,
        9104,
    ),
    (
        "DELETE",
        "/moderate",
        405,
        9105,
    ),
    (
        "PATCH",
        "/moderate",
        405,
        9106,
    ),
    (
        "POST",
        "/moderate/batch",
        200,
        9107,
    ),
    (
        "GET",
        "/moderate/batch",
        405,
        9108,
    ),
    (
        "PUT",
        "/moderate/batch",
        405,
        9109,
    ),
    (
        "DELETE",
        "/moderate/batch",
        405,
        9110,
    ),
    (
        "PATCH",
        "/moderate/batch",
        405,
        9111,
    ),
    (
        "GET",
        "/health",
        200,
        9112,
    ),
    (
        "POST",
        "/health",
        405,
        9113,
    ),
    (
        "PUT",
        "/health",
        405,
        9114,
    ),
    (
        "DELETE",
        "/health",
        405,
        9115,
    ),
    (
        "PATCH",
        "/health",
        405,
        9116,
    ),
    (
        "GET",
        "/metrics",
        200,
        9117,
    ),
    (
        "POST",
        "/metrics",
        405,
        9118,
    ),
    (
        "PUT",
        "/metrics",
        405,
        9119,
    ),
    (
        "DELETE",
        "/metrics",
        405,
        9120,
    ),
    (
        "PATCH",
        "/metrics",
        405,
        9121,
    ),
    (
        "GET",
        "/",
        200,
        9122,
    ),
    (
        "POST",
        "/",
        405,
        9123,
    ),
    (
        "PUT",
        "/",
        405,
        9124,
    ),
    (
        "DELETE",
        "/",
        405,
        9125,
    ),
    (
        "PATCH",
        "/",
        405,
        9126,
    ),
    (
        "GET",
        "/admin/wordbank/stats",
        200,
        9127,
    ),
    (
        "POST",
        "/admin/wordbank/stats",
        405,
        9128,
    ),
    (
        "PUT",
        "/admin/wordbank/stats",
        405,
        9129,
    ),
    (
        "DELETE",
        "/admin/wordbank/stats",
        405,
        9130,
    ),
    (
        "PATCH",
        "/admin/wordbank/stats",
        405,
        9131,
    ),
    (
        "GET",
        "/admin/wordbank/words",
        200,
        9132,
    ),
    (
        "POST",
        "/admin/wordbank/words",
        422,
        9133,
    ),
    (
        "PUT",
        "/admin/wordbank/words",
        405,
        9134,
    ),
    (
        "DELETE",
        "/admin/wordbank/words",
        422,
        9135,
    ),
    (
        "PATCH",
        "/admin/wordbank/words",
        405,
        9136,
    ),
    (
        "GET",
        "/admin/wordbank/export",
        200,
        9137,
    ),
    (
        "POST",
        "/admin/wordbank/export",
        405,
        9138,
    ),
    (
        "PUT",
        "/admin/wordbank/export",
        405,
        9139,
    ),
    (
        "DELETE",
        "/admin/wordbank/export",
        405,
        9140,
    ),
    (
        "PATCH",
        "/admin/wordbank/export",
        405,
        9141,
    ),
    (
        "GET",
        "/admin/wordbank/languages",
        200,
        9142,
    ),
    (
        "POST",
        "/admin/wordbank/languages",
        405,
        9143,
    ),
    (
        "PUT",
        "/admin/wordbank/languages",
        405,
        9144,
    ),
    (
        "DELETE",
        "/admin/wordbank/languages",
        405,
        9145,
    ),
    (
        "PATCH",
        "/admin/wordbank/languages",
        405,
        9146,
    ),
    (
        "GET",
        "/admin/wordbank/categories",
        200,
        9147,
    ),
    (
        "POST",
        "/admin/wordbank/categories",
        405,
        9148,
    ),
    (
        "PUT",
        "/admin/wordbank/categories",
        405,
        9149,
    ),
    (
        "DELETE",
        "/admin/wordbank/categories",
        405,
        9150,
    ),
    (
        "PATCH",
        "/admin/wordbank/categories",
        405,
        9151,
    ),
    (
        "POST",
        "/admin/wordbank/import",
        200,
        9152,
    ),
    (
        "GET",
        "/admin/wordbank/import",
        405,
        9153,
    ),
    (
        "PUT",
        "/admin/wordbank/import",
        405,
        9154,
    ),
    (
        "DELETE",
        "/admin/wordbank/import",
        405,
        9155,
    ),
    (
        "PATCH",
        "/admin/wordbank/import",
        405,
        9156,
    ),
    (
        "POST",
        "/admin/reload",
        200,
        9157,
    ),
    (
        "GET",
        "/admin/reload",
        405,
        9158,
    ),
    (
        "PUT",
        "/admin/reload",
        405,
        9159,
    ),
    (
        "DELETE",
        "/admin/reload",
        405,
        9160,
    ),
    (
        "PATCH",
        "/admin/reload",
        405,
        9161,
    ),
    (
        "GET",
        "/admin/app-config",
        200,
        9162,
    ),
    (
        "POST",
        "/admin/app-config",
        200,
        9163,
    ),
    (
        "PUT",
        "/admin/app-config",
        405,
        9164,
    ),
    (
        "DELETE",
        "/admin/app-config",
        405,
        9165,
    ),
    (
        "PATCH",
        "/admin/app-config",
        405,
        9166,
    ),
    (
        "GET",
        "/admin/app-config/demo",
        200,
        9167,
    ),
    (
        "POST",
        "/admin/app-config/demo",
        405,
        9168,
    ),
    (
        "PUT",
        "/admin/app-config/demo",
        405,
        9169,
    ),
    (
        "DELETE",
        "/admin/app-config/demo",
        405,
        9170,
    ),
    (
        "PATCH",
        "/admin/app-config/demo",
        405,
        9171,
    ),
    (
        "GET",
        "/admin/app-config/other",
        200,
        9172,
    ),
    (
        "POST",
        "/admin/app-config/other",
        405,
        9173,
    ),
    (
        "PUT",
        "/admin/app-config/other",
        405,
        9174,
    ),
    (
        "DELETE",
        "/admin/app-config/other",
        405,
        9175,
    ),
    (
        "PATCH",
        "/admin/app-config/other",
        405,
        9176,
    ),
    (
        "GET",
        "/admin/settings",
        200,
        9177,
    ),
    (
        "POST",
        "/admin/settings",
        200,
        9178,
    ),
    (
        "PUT",
        "/admin/settings",
        405,
        9179,
    ),
    (
        "DELETE",
        "/admin/settings",
        405,
        9180,
    ),
    (
        "PATCH",
        "/admin/settings",
        405,
        9181,
    ),
    (
        "GET",
        "/admin/logs",
        200,
        9182,
    ),
    (
        "POST",
        "/admin/logs",
        405,
        9183,
    ),
    (
        "PUT",
        "/admin/logs",
        405,
        9184,
    ),
    (
        "DELETE",
        "/admin/logs",
        405,
        9185,
    ),
    (
        "PATCH",
        "/admin/logs",
        405,
        9186,
    ),
    (
        "GET",
        "/admin/stats",
        200,
        9187,
    ),
    (
        "POST",
        "/admin/stats",
        405,
        9188,
    ),
    (
        "PUT",
        "/admin/stats",
        405,
        9189,
    ),
    (
        "DELETE",
        "/admin/stats",
        405,
        9190,
    ),
    (
        "PATCH",
        "/admin/stats",
        405,
        9191,
    ),
    (
        "GET",
        "/admin/health",
        200,
        9192,
    ),
    (
        "POST",
        "/admin/health",
        405,
        9193,
    ),
    (
        "PUT",
        "/admin/health",
        405,
        9194,
    ),
    (
        "DELETE",
        "/admin/health",
        405,
        9195,
    ),
    (
        "PATCH",
        "/admin/health",
        405,
        9196,
    ),
    (
        "GET",
        "/admin/spot-check",
        200,
        9197,
    ),
    (
        "POST",
        "/admin/spot-check",
        405,
        9198,
    ),
    (
        "PUT",
        "/admin/spot-check",
        405,
        9199,
    ),
    (
        "DELETE",
        "/admin/spot-check",
        405,
        9200,
    ),
    (
        "PATCH",
        "/admin/spot-check",
        405,
        9201,
    ),
)


class TestMethodRestriction(BaseTest):
    """Disallowed methods are rejected without error."""

    @pytest.mark.parametrize(
        (
            "method",
            "endpoint",
            "expected_status",
            "uid",
        ),
        _METHOD_RESTRICTION_CASES,
    )
    def test_method_restriction(
        self,
        client: Any,
        admin_headers: dict[str, str],
        method: str,
        endpoint: str,
        expected_status: int,
        uid: int,
    ) -> None:
        """Disallowed methods are rejected without error."""
        body = None
        if method == "POST" and "moderate" in endpoint:
            body = {"text": "hi"} if endpoint == "/moderate" else {"items": [{"text": "hi"}]}
        elif method == "POST" and endpoint == "/admin/wordbank/import":
            body = {"items": [{"word": "probe"}]}
        elif method == "POST" and endpoint == "/admin/app-config":
            body = {"app_name": "x", "score_threshold": 50}
        elif method == "POST" and endpoint == "/admin/settings":
            body = {"settings": {"WEIGHT_USER": 25}}
        headers = admin_headers if endpoint.startswith("/admin") else None
        response = client.request(method, endpoint, json=body, headers=headers)
        assert response.status_code == expected_status
