"""Phase 2 security tests (generated).

Header parity, CORS, auth bypass, injection, traversal, method
restrictions and encoded payloads; see tests/tools/phase2_generator.py."""

# multilingual fixtures use non-ASCII on purpose
from __future__ import annotations

from typing import Any

import pytest

from tests.base_test import BaseTest

_HEADER_PRESENT_CASES: tuple[tuple[str, str, str, int], ...] = (
    (
        "x-content-type-options",
        "GET",
        "/health",
        8532,
    ),
    (
        "x-content-type-options",
        "GET",
        "/health",
        8533,
    ),
    (
        "x-content-type-options",
        "GET",
        "/health",
        8534,
    ),
    (
        "x-content-type-options",
        "GET",
        "/health",
        8535,
    ),
    (
        "x-content-type-options",
        "POST",
        "/moderate",
        8536,
    ),
    (
        "x-content-type-options",
        "POST",
        "/moderate",
        8537,
    ),
    (
        "x-content-type-options",
        "POST",
        "/moderate",
        8538,
    ),
    (
        "x-content-type-options",
        "POST",
        "/moderate",
        8539,
    ),
    (
        "x-content-type-options",
        "GET",
        "/metrics",
        8540,
    ),
    (
        "x-content-type-options",
        "GET",
        "/metrics",
        8541,
    ),
    (
        "x-content-type-options",
        "GET",
        "/metrics",
        8542,
    ),
    (
        "x-content-type-options",
        "GET",
        "/metrics",
        8543,
    ),
    (
        "x-content-type-options",
        "POST",
        "/moderate/batch",
        8544,
    ),
    (
        "x-content-type-options",
        "POST",
        "/moderate/batch",
        8545,
    ),
    (
        "x-content-type-options",
        "POST",
        "/moderate/batch",
        8546,
    ),
    (
        "x-content-type-options",
        "POST",
        "/moderate/batch",
        8547,
    ),
    (
        "x-content-type-options",
        "GET",
        "/",
        8548,
    ),
    (
        "x-content-type-options",
        "GET",
        "/",
        8549,
    ),
    (
        "x-content-type-options",
        "GET",
        "/",
        8550,
    ),
    (
        "x-content-type-options",
        "GET",
        "/",
        8551,
    ),
    (
        "x-frame-options",
        "GET",
        "/health",
        8552,
    ),
    (
        "x-frame-options",
        "GET",
        "/health",
        8553,
    ),
    (
        "x-frame-options",
        "GET",
        "/health",
        8554,
    ),
    (
        "x-frame-options",
        "GET",
        "/health",
        8555,
    ),
    (
        "x-frame-options",
        "POST",
        "/moderate",
        8556,
    ),
    (
        "x-frame-options",
        "POST",
        "/moderate",
        8557,
    ),
    (
        "x-frame-options",
        "POST",
        "/moderate",
        8558,
    ),
    (
        "x-frame-options",
        "POST",
        "/moderate",
        8559,
    ),
    (
        "x-frame-options",
        "GET",
        "/metrics",
        8560,
    ),
    (
        "x-frame-options",
        "GET",
        "/metrics",
        8561,
    ),
    (
        "x-frame-options",
        "GET",
        "/metrics",
        8562,
    ),
    (
        "x-frame-options",
        "GET",
        "/metrics",
        8563,
    ),
    (
        "x-frame-options",
        "POST",
        "/moderate/batch",
        8564,
    ),
    (
        "x-frame-options",
        "POST",
        "/moderate/batch",
        8565,
    ),
    (
        "x-frame-options",
        "POST",
        "/moderate/batch",
        8566,
    ),
    (
        "x-frame-options",
        "POST",
        "/moderate/batch",
        8567,
    ),
    (
        "x-frame-options",
        "GET",
        "/",
        8568,
    ),
    (
        "x-frame-options",
        "GET",
        "/",
        8569,
    ),
    (
        "x-frame-options",
        "GET",
        "/",
        8570,
    ),
    (
        "x-frame-options",
        "GET",
        "/",
        8571,
    ),
    (
        "content-security-policy",
        "GET",
        "/health",
        8572,
    ),
    (
        "content-security-policy",
        "GET",
        "/health",
        8573,
    ),
    (
        "content-security-policy",
        "GET",
        "/health",
        8574,
    ),
    (
        "content-security-policy",
        "GET",
        "/health",
        8575,
    ),
    (
        "content-security-policy",
        "POST",
        "/moderate",
        8576,
    ),
    (
        "content-security-policy",
        "POST",
        "/moderate",
        8577,
    ),
    (
        "content-security-policy",
        "POST",
        "/moderate",
        8578,
    ),
    (
        "content-security-policy",
        "POST",
        "/moderate",
        8579,
    ),
    (
        "content-security-policy",
        "GET",
        "/metrics",
        8580,
    ),
    (
        "content-security-policy",
        "GET",
        "/metrics",
        8581,
    ),
    (
        "content-security-policy",
        "GET",
        "/metrics",
        8582,
    ),
    (
        "content-security-policy",
        "GET",
        "/metrics",
        8583,
    ),
    (
        "content-security-policy",
        "POST",
        "/moderate/batch",
        8584,
    ),
    (
        "content-security-policy",
        "POST",
        "/moderate/batch",
        8585,
    ),
    (
        "content-security-policy",
        "POST",
        "/moderate/batch",
        8586,
    ),
    (
        "content-security-policy",
        "POST",
        "/moderate/batch",
        8587,
    ),
    (
        "content-security-policy",
        "GET",
        "/",
        8588,
    ),
    (
        "content-security-policy",
        "GET",
        "/",
        8589,
    ),
    (
        "content-security-policy",
        "GET",
        "/",
        8590,
    ),
    (
        "content-security-policy",
        "GET",
        "/",
        8591,
    ),
    (
        "strict-transport-security",
        "GET",
        "/health",
        8592,
    ),
    (
        "strict-transport-security",
        "GET",
        "/health",
        8593,
    ),
    (
        "strict-transport-security",
        "GET",
        "/health",
        8594,
    ),
    (
        "strict-transport-security",
        "GET",
        "/health",
        8595,
    ),
    (
        "strict-transport-security",
        "POST",
        "/moderate",
        8596,
    ),
    (
        "strict-transport-security",
        "POST",
        "/moderate",
        8597,
    ),
    (
        "strict-transport-security",
        "POST",
        "/moderate",
        8598,
    ),
    (
        "strict-transport-security",
        "POST",
        "/moderate",
        8599,
    ),
    (
        "strict-transport-security",
        "GET",
        "/metrics",
        8600,
    ),
    (
        "strict-transport-security",
        "GET",
        "/metrics",
        8601,
    ),
    (
        "strict-transport-security",
        "GET",
        "/metrics",
        8602,
    ),
    (
        "strict-transport-security",
        "GET",
        "/metrics",
        8603,
    ),
    (
        "strict-transport-security",
        "POST",
        "/moderate/batch",
        8604,
    ),
    (
        "strict-transport-security",
        "POST",
        "/moderate/batch",
        8605,
    ),
    (
        "strict-transport-security",
        "POST",
        "/moderate/batch",
        8606,
    ),
    (
        "strict-transport-security",
        "POST",
        "/moderate/batch",
        8607,
    ),
    (
        "strict-transport-security",
        "GET",
        "/",
        8608,
    ),
    (
        "strict-transport-security",
        "GET",
        "/",
        8609,
    ),
    (
        "strict-transport-security",
        "GET",
        "/",
        8610,
    ),
    (
        "strict-transport-security",
        "GET",
        "/",
        8611,
    ),
    (
        "x-xss-protection",
        "GET",
        "/health",
        8612,
    ),
    (
        "x-xss-protection",
        "GET",
        "/health",
        8613,
    ),
    (
        "x-xss-protection",
        "GET",
        "/health",
        8614,
    ),
    (
        "x-xss-protection",
        "GET",
        "/health",
        8615,
    ),
    (
        "x-xss-protection",
        "POST",
        "/moderate",
        8616,
    ),
    (
        "x-xss-protection",
        "POST",
        "/moderate",
        8617,
    ),
    (
        "x-xss-protection",
        "POST",
        "/moderate",
        8618,
    ),
    (
        "x-xss-protection",
        "POST",
        "/moderate",
        8619,
    ),
    (
        "x-xss-protection",
        "GET",
        "/metrics",
        8620,
    ),
    (
        "x-xss-protection",
        "GET",
        "/metrics",
        8621,
    ),
    (
        "x-xss-protection",
        "GET",
        "/metrics",
        8622,
    ),
    (
        "x-xss-protection",
        "GET",
        "/metrics",
        8623,
    ),
    (
        "x-xss-protection",
        "POST",
        "/moderate/batch",
        8624,
    ),
    (
        "x-xss-protection",
        "POST",
        "/moderate/batch",
        8625,
    ),
    (
        "x-xss-protection",
        "POST",
        "/moderate/batch",
        8626,
    ),
    (
        "x-xss-protection",
        "POST",
        "/moderate/batch",
        8627,
    ),
    (
        "x-xss-protection",
        "GET",
        "/",
        8628,
    ),
    (
        "x-xss-protection",
        "GET",
        "/",
        8629,
    ),
    (
        "x-xss-protection",
        "GET",
        "/",
        8630,
    ),
    (
        "x-xss-protection",
        "GET",
        "/",
        8631,
    ),
)


class TestHeaderPresent(BaseTest):
    """Every security header appears on every endpoint."""

    @pytest.mark.parametrize(
        (
            "header",
            "method",
            "endpoint",
            "uid",
        ),
        _HEADER_PRESENT_CASES,
    )
    def test_header_present(
        self, client: Any, header: str, method: str, endpoint: str, uid: int
    ) -> None:
        """Every security header appears on every endpoint."""
        payload = {"text": "hi", "app_name": "a"} if endpoint == "/moderate" else None
        if method == "POST" and payload is not None:
            response = client.post(endpoint, json=payload)
        else:
            response = client.request(method, endpoint)
        assert header in response.headers
