"""Phase 2 security tests (generated).

Header parity, CORS, auth bypass, injection, traversal, method
restrictions and encoded payloads; see tests/tools/phase2_generator.py."""

# multilingual fixtures use non-ASCII on purpose
from __future__ import annotations

from typing import Any

import pytest

from tests.base_test import BaseTest

_AUTH_REJECTED_CASES: tuple[tuple[str, str, int], ...] = (
    (
        "",
        "/admin/wordbank/stats",
        8772,
    ),
    (
        "",
        "/admin/wordbank/words",
        8773,
    ),
    (
        "",
        "/admin/wordbank/export",
        8774,
    ),
    (
        "",
        "/admin/wordbank/languages",
        8775,
    ),
    (
        "",
        "/admin/wordbank/categories",
        8776,
    ),
    (
        "",
        "/admin/app-config",
        8777,
    ),
    (
        "",
        "/admin/settings",
        8778,
    ),
    (
        "",
        "/admin/logs",
        8779,
    ),
    (
        "",
        "/admin/health",
        8780,
    ),
    (
        "",
        "/admin/spot-check",
        8781,
    ),
    (
        " ",
        "/admin/wordbank/stats",
        8782,
    ),
    (
        " ",
        "/admin/wordbank/words",
        8783,
    ),
    (
        " ",
        "/admin/wordbank/export",
        8784,
    ),
    (
        " ",
        "/admin/wordbank/languages",
        8785,
    ),
    (
        " ",
        "/admin/wordbank/categories",
        8786,
    ),
    (
        " ",
        "/admin/app-config",
        8787,
    ),
    (
        " ",
        "/admin/settings",
        8788,
    ),
    (
        " ",
        "/admin/logs",
        8789,
    ),
    (
        " ",
        "/admin/health",
        8790,
    ),
    (
        " ",
        "/admin/spot-check",
        8791,
    ),
    (
        "null",
        "/admin/wordbank/stats",
        8792,
    ),
    (
        "null",
        "/admin/wordbank/words",
        8793,
    ),
    (
        "null",
        "/admin/wordbank/export",
        8794,
    ),
    (
        "null",
        "/admin/wordbank/languages",
        8795,
    ),
    (
        "null",
        "/admin/wordbank/categories",
        8796,
    ),
    (
        "null",
        "/admin/app-config",
        8797,
    ),
    (
        "null",
        "/admin/settings",
        8798,
    ),
    (
        "null",
        "/admin/logs",
        8799,
    ),
    (
        "null",
        "/admin/health",
        8800,
    ),
    (
        "null",
        "/admin/spot-check",
        8801,
    ),
    (
        "None",
        "/admin/wordbank/stats",
        8802,
    ),
    (
        "None",
        "/admin/wordbank/words",
        8803,
    ),
    (
        "None",
        "/admin/wordbank/export",
        8804,
    ),
    (
        "None",
        "/admin/wordbank/languages",
        8805,
    ),
    (
        "None",
        "/admin/wordbank/categories",
        8806,
    ),
    (
        "None",
        "/admin/app-config",
        8807,
    ),
    (
        "None",
        "/admin/settings",
        8808,
    ),
    (
        "None",
        "/admin/logs",
        8809,
    ),
    (
        "None",
        "/admin/health",
        8810,
    ),
    (
        "None",
        "/admin/spot-check",
        8811,
    ),
    (
        "CHANGE_ME",
        "/admin/wordbank/stats",
        8812,
    ),
    (
        "CHANGE_ME",
        "/admin/wordbank/words",
        8813,
    ),
    (
        "CHANGE_ME",
        "/admin/wordbank/export",
        8814,
    ),
    (
        "CHANGE_ME",
        "/admin/wordbank/languages",
        8815,
    ),
    (
        "CHANGE_ME",
        "/admin/wordbank/categories",
        8816,
    ),
    (
        "CHANGE_ME",
        "/admin/app-config",
        8817,
    ),
    (
        "CHANGE_ME",
        "/admin/settings",
        8818,
    ),
    (
        "CHANGE_ME",
        "/admin/logs",
        8819,
    ),
    (
        "CHANGE_ME",
        "/admin/health",
        8820,
    ),
    (
        "CHANGE_ME",
        "/admin/spot-check",
        8821,
    ),
    (
        "wrong-key",
        "/admin/wordbank/stats",
        8822,
    ),
    (
        "wrong-key",
        "/admin/wordbank/words",
        8823,
    ),
    (
        "wrong-key",
        "/admin/wordbank/export",
        8824,
    ),
    (
        "wrong-key",
        "/admin/wordbank/languages",
        8825,
    ),
    (
        "wrong-key",
        "/admin/wordbank/categories",
        8826,
    ),
    (
        "wrong-key",
        "/admin/app-config",
        8827,
    ),
    (
        "wrong-key",
        "/admin/settings",
        8828,
    ),
    (
        "wrong-key",
        "/admin/logs",
        8829,
    ),
    (
        "wrong-key",
        "/admin/health",
        8830,
    ),
    (
        "wrong-key",
        "/admin/spot-check",
        8831,
    ),
    (
        "test-admin-key ",
        "/admin/wordbank/stats",
        8832,
    ),
    (
        "test-admin-key ",
        "/admin/wordbank/words",
        8833,
    ),
    (
        "test-admin-key ",
        "/admin/wordbank/export",
        8834,
    ),
    (
        "test-admin-key ",
        "/admin/wordbank/languages",
        8835,
    ),
    (
        "test-admin-key ",
        "/admin/wordbank/categories",
        8836,
    ),
    (
        "test-admin-key ",
        "/admin/app-config",
        8837,
    ),
    (
        "test-admin-key ",
        "/admin/settings",
        8838,
    ),
    (
        "test-admin-key ",
        "/admin/logs",
        8839,
    ),
    (
        "test-admin-key ",
        "/admin/health",
        8840,
    ),
    (
        "test-admin-key ",
        "/admin/spot-check",
        8841,
    ),
    (
        "TEST-ADMIN-KEY",
        "/admin/wordbank/stats",
        8842,
    ),
    (
        "TEST-ADMIN-KEY",
        "/admin/wordbank/words",
        8843,
    ),
    (
        "TEST-ADMIN-KEY",
        "/admin/wordbank/export",
        8844,
    ),
    (
        "TEST-ADMIN-KEY",
        "/admin/wordbank/languages",
        8845,
    ),
    (
        "TEST-ADMIN-KEY",
        "/admin/wordbank/categories",
        8846,
    ),
    (
        "TEST-ADMIN-KEY",
        "/admin/app-config",
        8847,
    ),
    (
        "TEST-ADMIN-KEY",
        "/admin/settings",
        8848,
    ),
    (
        "TEST-ADMIN-KEY",
        "/admin/logs",
        8849,
    ),
    (
        "TEST-ADMIN-KEY",
        "/admin/health",
        8850,
    ),
    (
        "TEST-ADMIN-KEY",
        "/admin/spot-check",
        8851,
    ),
    (
        "bearer-token",
        "/admin/wordbank/stats",
        8852,
    ),
    (
        "bearer-token",
        "/admin/wordbank/words",
        8853,
    ),
    (
        "bearer-token",
        "/admin/wordbank/export",
        8854,
    ),
    (
        "bearer-token",
        "/admin/wordbank/languages",
        8855,
    ),
    (
        "bearer-token",
        "/admin/wordbank/categories",
        8856,
    ),
    (
        "bearer-token",
        "/admin/app-config",
        8857,
    ),
    (
        "bearer-token",
        "/admin/settings",
        8858,
    ),
    (
        "bearer-token",
        "/admin/logs",
        8859,
    ),
    (
        "bearer-token",
        "/admin/health",
        8860,
    ),
    (
        "bearer-token",
        "/admin/spot-check",
        8861,
    ),
    (
        "leaked-secret",
        "/admin/wordbank/stats",
        8862,
    ),
    (
        "leaked-secret",
        "/admin/wordbank/words",
        8863,
    ),
    (
        "leaked-secret",
        "/admin/wordbank/export",
        8864,
    ),
    (
        "leaked-secret",
        "/admin/wordbank/languages",
        8865,
    ),
    (
        "leaked-secret",
        "/admin/wordbank/categories",
        8866,
    ),
    (
        "leaked-secret",
        "/admin/app-config",
        8867,
    ),
    (
        "leaked-secret",
        "/admin/settings",
        8868,
    ),
    (
        "leaked-secret",
        "/admin/logs",
        8869,
    ),
    (
        "leaked-secret",
        "/admin/health",
        8870,
    ),
    (
        "leaked-secret",
        "/admin/spot-check",
        8871,
    ),
)


class TestAuthRejected(BaseTest):
    """Invalid credentials are rejected on admin endpoints."""

    @pytest.mark.parametrize(
        (
            "key",
            "endpoint",
            "uid",
        ),
        _AUTH_REJECTED_CASES,
    )
    def test_auth_rejected(self, client: Any, key: str, endpoint: str, uid: int) -> None:
        """Invalid credentials are rejected on admin endpoints."""
        response = client.get(endpoint, headers={"X-API-Key": key})
        assert response.status_code == 401
        bearer = client.get(endpoint, headers={"Authorization": f"Bearer {key}"})
        assert bearer.status_code == 401
