"""Phase 2 security tests (generated).

Header parity, CORS, auth bypass, injection, traversal, method
restrictions and encoded payloads; see tests/tools/phase2_generator.py."""

# multilingual fixtures use non-ASCII on purpose
from __future__ import annotations

from typing import Any

import pytest

from tests.base_test import BaseTest

_CORS_PREFLIGHT_CASES: tuple[tuple[str, str, int], ...] = (
    (
        "http://localhost:3000",
        "GET",
        8652,
    ),
    (
        "http://localhost:3000",
        "GET",
        8653,
    ),
    (
        "http://localhost:3000",
        "GET",
        8654,
    ),
    (
        "http://localhost:3000",
        "GET",
        8655,
    ),
    (
        "http://localhost:3000",
        "POST",
        8656,
    ),
    (
        "http://localhost:3000",
        "POST",
        8657,
    ),
    (
        "http://localhost:3000",
        "POST",
        8658,
    ),
    (
        "http://localhost:3000",
        "POST",
        8659,
    ),
    (
        "http://localhost:3000",
        "PUT",
        8660,
    ),
    (
        "http://localhost:3000",
        "PUT",
        8661,
    ),
    (
        "http://localhost:3000",
        "PUT",
        8662,
    ),
    (
        "http://localhost:3000",
        "PUT",
        8663,
    ),
    (
        "http://localhost:3000",
        "DELETE",
        8664,
    ),
    (
        "http://localhost:3000",
        "DELETE",
        8665,
    ),
    (
        "http://localhost:3000",
        "DELETE",
        8666,
    ),
    (
        "http://localhost:3000",
        "DELETE",
        8667,
    ),
    (
        "http://localhost:3000",
        "OPTIONS",
        8668,
    ),
    (
        "http://localhost:3000",
        "OPTIONS",
        8669,
    ),
    (
        "http://localhost:3000",
        "OPTIONS",
        8670,
    ),
    (
        "http://localhost:3000",
        "OPTIONS",
        8671,
    ),
    (
        "https://mod.example.com",
        "GET",
        8672,
    ),
    (
        "https://mod.example.com",
        "GET",
        8673,
    ),
    (
        "https://mod.example.com",
        "GET",
        8674,
    ),
    (
        "https://mod.example.com",
        "GET",
        8675,
    ),
    (
        "https://mod.example.com",
        "POST",
        8676,
    ),
    (
        "https://mod.example.com",
        "POST",
        8677,
    ),
    (
        "https://mod.example.com",
        "POST",
        8678,
    ),
    (
        "https://mod.example.com",
        "POST",
        8679,
    ),
    (
        "https://mod.example.com",
        "PUT",
        8680,
    ),
    (
        "https://mod.example.com",
        "PUT",
        8681,
    ),
    (
        "https://mod.example.com",
        "PUT",
        8682,
    ),
    (
        "https://mod.example.com",
        "PUT",
        8683,
    ),
    (
        "https://mod.example.com",
        "DELETE",
        8684,
    ),
    (
        "https://mod.example.com",
        "DELETE",
        8685,
    ),
    (
        "https://mod.example.com",
        "DELETE",
        8686,
    ),
    (
        "https://mod.example.com",
        "DELETE",
        8687,
    ),
    (
        "https://mod.example.com",
        "OPTIONS",
        8688,
    ),
    (
        "https://mod.example.com",
        "OPTIONS",
        8689,
    ),
    (
        "https://mod.example.com",
        "OPTIONS",
        8690,
    ),
    (
        "https://mod.example.com",
        "OPTIONS",
        8691,
    ),
    (
        "http://evil.example",
        "GET",
        8692,
    ),
    (
        "http://evil.example",
        "GET",
        8693,
    ),
    (
        "http://evil.example",
        "GET",
        8694,
    ),
    (
        "http://evil.example",
        "GET",
        8695,
    ),
    (
        "http://evil.example",
        "POST",
        8696,
    ),
    (
        "http://evil.example",
        "POST",
        8697,
    ),
    (
        "http://evil.example",
        "POST",
        8698,
    ),
    (
        "http://evil.example",
        "POST",
        8699,
    ),
    (
        "http://evil.example",
        "PUT",
        8700,
    ),
    (
        "http://evil.example",
        "PUT",
        8701,
    ),
    (
        "http://evil.example",
        "PUT",
        8702,
    ),
    (
        "http://evil.example",
        "PUT",
        8703,
    ),
    (
        "http://evil.example",
        "DELETE",
        8704,
    ),
    (
        "http://evil.example",
        "DELETE",
        8705,
    ),
    (
        "http://evil.example",
        "DELETE",
        8706,
    ),
    (
        "http://evil.example",
        "DELETE",
        8707,
    ),
    (
        "http://evil.example",
        "OPTIONS",
        8708,
    ),
    (
        "http://evil.example",
        "OPTIONS",
        8709,
    ),
    (
        "http://evil.example",
        "OPTIONS",
        8710,
    ),
    (
        "http://evil.example",
        "OPTIONS",
        8711,
    ),
    (
        "https://attacker.com",
        "GET",
        8712,
    ),
    (
        "https://attacker.com",
        "GET",
        8713,
    ),
    (
        "https://attacker.com",
        "GET",
        8714,
    ),
    (
        "https://attacker.com",
        "GET",
        8715,
    ),
    (
        "https://attacker.com",
        "POST",
        8716,
    ),
    (
        "https://attacker.com",
        "POST",
        8717,
    ),
    (
        "https://attacker.com",
        "POST",
        8718,
    ),
    (
        "https://attacker.com",
        "POST",
        8719,
    ),
    (
        "https://attacker.com",
        "PUT",
        8720,
    ),
    (
        "https://attacker.com",
        "PUT",
        8721,
    ),
    (
        "https://attacker.com",
        "PUT",
        8722,
    ),
    (
        "https://attacker.com",
        "PUT",
        8723,
    ),
    (
        "https://attacker.com",
        "DELETE",
        8724,
    ),
    (
        "https://attacker.com",
        "DELETE",
        8725,
    ),
    (
        "https://attacker.com",
        "DELETE",
        8726,
    ),
    (
        "https://attacker.com",
        "DELETE",
        8727,
    ),
    (
        "https://attacker.com",
        "OPTIONS",
        8728,
    ),
    (
        "https://attacker.com",
        "OPTIONS",
        8729,
    ),
    (
        "https://attacker.com",
        "OPTIONS",
        8730,
    ),
    (
        "https://attacker.com",
        "OPTIONS",
        8731,
    ),
    (
        "null",
        "GET",
        8732,
    ),
    (
        "null",
        "GET",
        8733,
    ),
    (
        "null",
        "GET",
        8734,
    ),
    (
        "null",
        "GET",
        8735,
    ),
    (
        "null",
        "POST",
        8736,
    ),
    (
        "null",
        "POST",
        8737,
    ),
    (
        "null",
        "POST",
        8738,
    ),
    (
        "null",
        "POST",
        8739,
    ),
    (
        "null",
        "PUT",
        8740,
    ),
    (
        "null",
        "PUT",
        8741,
    ),
    (
        "null",
        "PUT",
        8742,
    ),
    (
        "null",
        "PUT",
        8743,
    ),
    (
        "null",
        "DELETE",
        8744,
    ),
    (
        "null",
        "DELETE",
        8745,
    ),
    (
        "null",
        "DELETE",
        8746,
    ),
    (
        "null",
        "DELETE",
        8747,
    ),
    (
        "null",
        "OPTIONS",
        8748,
    ),
    (
        "null",
        "OPTIONS",
        8749,
    ),
    (
        "null",
        "OPTIONS",
        8750,
    ),
    (
        "null",
        "OPTIONS",
        8751,
    ),
)


class TestCorsPreflight(BaseTest):
    """Preflight and CORS responses are handled without error."""

    @pytest.mark.parametrize(
        (
            "origin",
            "method",
            "uid",
        ),
        _CORS_PREFLIGHT_CASES,
    )
    def test_cors_preflight(self, client: Any, origin: str, method: str, uid: int) -> None:
        """Preflight and CORS responses are handled without error."""
        response = client.options(
            "/moderate",
            headers={"Origin": origin, "Access-Control-Request-Method": method},
        )
        assert response.status_code in (200, 400, 405)
