"""Phase 2 admin API tests (generated).

Word CRUD, import/export, app policies, settings, logs and dashboard
stats; see tests/tools/phase2_generator.py."""

# multilingual fixtures use non-ASCII on purpose
from __future__ import annotations

from typing import Any

import pytest

from tests.base_test import BaseTest

_WORD_CRUD_CASES: tuple[tuple[str, str, int, str, int], ...] = (
    (
        "crud_sexual_3_en",
        "sexual",
        3,
        "en",
        7329,
    ),
    (
        "crud_sexual_3_zh-CN",
        "sexual",
        3,
        "zh-CN",
        7330,
    ),
    (
        "crud_sexual_3_ru",
        "sexual",
        3,
        "ru",
        7331,
    ),
    (
        "crud_sexual_3_ar",
        "sexual",
        3,
        "ar",
        7332,
    ),
    (
        "crud_sexual_3_ja",
        "sexual",
        3,
        "ja",
        7333,
    ),
    (
        "crud_sexual_5_en",
        "sexual",
        5,
        "en",
        7334,
    ),
    (
        "crud_sexual_5_zh-CN",
        "sexual",
        5,
        "zh-CN",
        7335,
    ),
    (
        "crud_sexual_5_ru",
        "sexual",
        5,
        "ru",
        7336,
    ),
    (
        "crud_sexual_5_ar",
        "sexual",
        5,
        "ar",
        7337,
    ),
    (
        "crud_sexual_5_ja",
        "sexual",
        5,
        "ja",
        7338,
    ),
    (
        "crud_sexual_7_en",
        "sexual",
        7,
        "en",
        7339,
    ),
    (
        "crud_sexual_7_zh-CN",
        "sexual",
        7,
        "zh-CN",
        7340,
    ),
    (
        "crud_sexual_7_ru",
        "sexual",
        7,
        "ru",
        7341,
    ),
    (
        "crud_sexual_7_ar",
        "sexual",
        7,
        "ar",
        7342,
    ),
    (
        "crud_sexual_7_ja",
        "sexual",
        7,
        "ja",
        7343,
    ),
    (
        "crud_sexual_10_en",
        "sexual",
        10,
        "en",
        7344,
    ),
    (
        "crud_sexual_10_zh-CN",
        "sexual",
        10,
        "zh-CN",
        7345,
    ),
    (
        "crud_sexual_10_ru",
        "sexual",
        10,
        "ru",
        7346,
    ),
    (
        "crud_sexual_10_ar",
        "sexual",
        10,
        "ar",
        7347,
    ),
    (
        "crud_sexual_10_ja",
        "sexual",
        10,
        "ja",
        7348,
    ),
    (
        "crud_political_0_en",
        "political",
        0,
        "en",
        7349,
    ),
    (
        "crud_political_0_zh-CN",
        "political",
        0,
        "zh-CN",
        7350,
    ),
    (
        "crud_political_0_ru",
        "political",
        0,
        "ru",
        7351,
    ),
    (
        "crud_political_0_ar",
        "political",
        0,
        "ar",
        7352,
    ),
    (
        "crud_political_0_ja",
        "political",
        0,
        "ja",
        7353,
    ),
    (
        "crud_political_1_en",
        "political",
        1,
        "en",
        7354,
    ),
    (
        "crud_political_1_zh-CN",
        "political",
        1,
        "zh-CN",
        7355,
    ),
    (
        "crud_political_1_ru",
        "political",
        1,
        "ru",
        7356,
    ),
    (
        "crud_political_1_ar",
        "political",
        1,
        "ar",
        7357,
    ),
    (
        "crud_political_1_ja",
        "political",
        1,
        "ja",
        7358,
    ),
    (
        "crud_political_3_en",
        "political",
        3,
        "en",
        7359,
    ),
    (
        "crud_political_3_zh-CN",
        "political",
        3,
        "zh-CN",
        7360,
    ),
    (
        "crud_political_3_ru",
        "political",
        3,
        "ru",
        7361,
    ),
    (
        "crud_political_3_ar",
        "political",
        3,
        "ar",
        7362,
    ),
    (
        "crud_political_3_ja",
        "political",
        3,
        "ja",
        7363,
    ),
    (
        "crud_political_5_en",
        "political",
        5,
        "en",
        7364,
    ),
    (
        "crud_political_5_zh-CN",
        "political",
        5,
        "zh-CN",
        7365,
    ),
    (
        "crud_political_5_ru",
        "political",
        5,
        "ru",
        7366,
    ),
    (
        "crud_political_5_ar",
        "political",
        5,
        "ar",
        7367,
    ),
    (
        "crud_political_5_ja",
        "political",
        5,
        "ja",
        7368,
    ),
    (
        "crud_political_7_en",
        "political",
        7,
        "en",
        7369,
    ),
    (
        "crud_political_7_zh-CN",
        "political",
        7,
        "zh-CN",
        7370,
    ),
    (
        "crud_political_7_ru",
        "political",
        7,
        "ru",
        7371,
    ),
    (
        "crud_political_7_ar",
        "political",
        7,
        "ar",
        7372,
    ),
    (
        "crud_political_7_ja",
        "political",
        7,
        "ja",
        7373,
    ),
    (
        "crud_political_10_en",
        "political",
        10,
        "en",
        7374,
    ),
    (
        "crud_political_10_zh-CN",
        "political",
        10,
        "zh-CN",
        7375,
    ),
    (
        "crud_political_10_ru",
        "political",
        10,
        "ru",
        7376,
    ),
    (
        "crud_political_10_ar",
        "political",
        10,
        "ar",
        7377,
    ),
    (
        "crud_political_10_ja",
        "political",
        10,
        "ja",
        7378,
    ),
)


class TestWordCrud(BaseTest):
    """Adding, listing and deleting a custom word round-trips."""

    @pytest.mark.parametrize(
        (
            "word",
            "category",
            "severity",
            "language",
            "uid",
        ),
        _WORD_CRUD_CASES,
    )
    def test_word_crud(
        self,
        client: Any,
        admin_headers: dict[str, str],
        word: str,
        category: str,
        severity: int,
        language: str,
        uid: int,
    ) -> None:
        """Adding, listing and deleting a custom word round-trips."""
        payload = {"word": word, "category": category, "severity": severity, "language": language}
        created = client.post(
            "/admin/wordbank/words",
            headers=admin_headers,
            json=payload,
        )
        assert created.status_code == 201
        response = client.get("/admin/wordbank/words", headers=admin_headers)
        assert response.status_code == 200
        assert any(entry["word"] == word.lower() for entry in response.json())


_IMPORT_WORDS_CASES: tuple[tuple[int, int, int], ...] = (
    (
        1,
        0,
        7469,
    ),
    (
        1,
        1,
        7470,
    ),
    (
        1,
        2,
        7471,
    ),
    (
        1,
        3,
        7472,
    ),
    (
        1,
        4,
        7473,
    ),
    (
        1,
        5,
        7474,
    ),
    (
        1,
        6,
        7475,
    ),
    (
        1,
        7,
        7476,
    ),
    (
        1,
        8,
        7477,
    ),
    (
        1,
        9,
        7478,
    ),
    (
        1,
        10,
        7479,
    ),
    (
        1,
        11,
        7480,
    ),
    (
        1,
        12,
        7481,
    ),
    (
        1,
        13,
        7482,
    ),
    (
        1,
        14,
        7483,
    ),
    (
        2,
        0,
        7484,
    ),
    (
        2,
        1,
        7485,
    ),
    (
        2,
        2,
        7486,
    ),
    (
        2,
        3,
        7487,
    ),
    (
        2,
        4,
        7488,
    ),
    (
        2,
        5,
        7489,
    ),
    (
        2,
        6,
        7490,
    ),
    (
        2,
        7,
        7491,
    ),
    (
        2,
        8,
        7492,
    ),
    (
        2,
        9,
        7493,
    ),
    (
        2,
        10,
        7494,
    ),
    (
        2,
        11,
        7495,
    ),
    (
        2,
        12,
        7496,
    ),
    (
        2,
        13,
        7497,
    ),
    (
        2,
        14,
        7498,
    ),
    (
        5,
        0,
        7499,
    ),
    (
        5,
        1,
        7500,
    ),
    (
        5,
        2,
        7501,
    ),
    (
        5,
        3,
        7502,
    ),
    (
        5,
        4,
        7503,
    ),
    (
        5,
        5,
        7504,
    ),
    (
        5,
        6,
        7505,
    ),
    (
        5,
        7,
        7506,
    ),
    (
        5,
        8,
        7507,
    ),
    (
        5,
        9,
        7508,
    ),
    (
        5,
        10,
        7509,
    ),
    (
        5,
        11,
        7510,
    ),
    (
        5,
        12,
        7511,
    ),
    (
        5,
        13,
        7512,
    ),
    (
        5,
        14,
        7513,
    ),
    (
        10,
        0,
        7514,
    ),
    (
        10,
        1,
        7515,
    ),
    (
        10,
        2,
        7516,
    ),
    (
        10,
        3,
        7517,
    ),
    (
        10,
        4,
        7518,
    ),
)


class TestImportWords(BaseTest):
    """Bulk import reports the imported count."""

    @pytest.mark.parametrize(
        (
            "size",
            "scenario",
            "uid",
        ),
        _IMPORT_WORDS_CASES,
    )
    def test_import_words(
        self, client: Any, admin_headers: dict[str, str], size: int, scenario: int, uid: int
    ) -> None:
        """Bulk import reports the imported count."""
        items = [{"word": f"imp{index}_{scenario}"} for index in range(size)]
        response = client.post(
            "/admin/wordbank/import", headers=admin_headers, json={"items": items}
        )
        assert response.status_code == 200
        assert response.json()["imported"] == size
        stats = client.get("/admin/wordbank/stats", headers=admin_headers).json()
        assert stats["customWords"] >= size
