"""Phase 2 runtime settings tests (generated).

Catalog metadata, read-only protection, probed valid/invalid matrices
and typed coercion; see tests/tools/phase2_generator.py."""

# multilingual fixtures use non-ASCII on purpose
from __future__ import annotations

from typing import Any

import pytest

from app.settings_service import SettingsService
from tests.base_test import BaseTest

_INVALID_UPDATE_CASES: tuple[tuple[str, int, int], ...] = (
    (
        "AI_TARGET_PERCENTAGE",
        -5,
        6080,
    ),
    (
        "AI_TARGET_PERCENTAGE",
        -1,
        6081,
    ),
    (
        "AI_TARGET_PERCENTAGE",
        1000000000,
        6082,
    ),
    (
        "AI_TARGET_PERCENTAGE",
        "not-a-number",
        6083,
    ),
    (
        "ALLOWED_ORIGINS",
        "",
        6084,
    ),
    (
        "APP_CONFIG_DB_PATH",
        "",
        6085,
    ),
    (
        "APP_HOST",
        "",
        6086,
    ),
    (
        "AUTO_TUNING_BATCH_HOUR",
        -5,
        6087,
    ),
    (
        "AUTO_TUNING_BATCH_HOUR",
        -1,
        6088,
    ),
    (
        "AUTO_TUNING_BATCH_HOUR",
        1000000000,
        6089,
    ),
    (
        "AUTO_TUNING_BATCH_HOUR",
        "not-a-number",
        6090,
    ),
    (
        "AUTO_TUNING_ENABLED",
        "maybe",
        6091,
    ),
    (
        "AUTO_TUNING_ENABLED",
        "bogus",
        6092,
    ),
    (
        "AUTO_TUNING_ENABLED",
        5,
        6093,
    ),
    (
        "AUTO_TUNING_ENABLED",
        "not-bool",
        6094,
    ),
    (
        "BLOOM_FILTER_CAPACITY",
        "",
        6095,
    ),
    (
        "BLOOM_FILTER_ERROR_RATE",
        "",
        6096,
    ),
    (
        "CACHE_MAX_SIZE",
        -5,
        6097,
    ),
    (
        "CACHE_MAX_SIZE",
        -1,
        6098,
    ),
    (
        "CACHE_MAX_SIZE",
        0,
        6099,
    ),
    (
        "CACHE_MAX_SIZE",
        1000000000,
        6100,
    ),
    (
        "CACHE_MAX_SIZE",
        "not-a-number",
        6101,
    ),
    (
        "CACHE_TTL_SECONDS",
        -5,
        6102,
    ),
    (
        "CACHE_TTL_SECONDS",
        -1,
        6103,
    ),
    (
        "CACHE_TTL_SECONDS",
        0,
        6104,
    ),
    (
        "CACHE_TTL_SECONDS",
        1000000000,
        6105,
    ),
    (
        "CACHE_TTL_SECONDS",
        "not-a-number",
        6106,
    ),
    (
        "CUSTOM_WORDS_PATH",
        "",
        6107,
    ),
    (
        "CUSTOM_WORDS_STORAGE",
        "",
        6108,
    ),
    (
        "DETECTOR_THREAD_POOL_SIZE",
        -5,
        6109,
    ),
    (
        "DETECTOR_THREAD_POOL_SIZE",
        -1,
        6110,
    ),
    (
        "DETECTOR_THREAD_POOL_SIZE",
        0,
        6111,
    ),
    (
        "DETECTOR_THREAD_POOL_SIZE",
        1000000000,
        6112,
    ),
    (
        "DETECTOR_THREAD_POOL_SIZE",
        "not-a-number",
        6113,
    ),
    (
        "ENABLE_BADWORDS_PY",
        "maybe",
        6114,
    ),
    (
        "ENABLE_BADWORDS_PY",
        "bogus",
        6115,
    ),
    (
        "ENABLE_BADWORDS_PY",
        5,
        6116,
    ),
    (
        "ENABLE_BADWORDS_PY",
        "not-bool",
        6117,
    ),
    (
        "ENABLE_GANGAJAL",
        "maybe",
        6118,
    ),
    (
        "ENABLE_GANGAJAL",
        "bogus",
        6119,
    ),
    (
        "ENABLE_GANGAJAL",
        5,
        6120,
    ),
    (
        "ENABLE_GANGAJAL",
        "not-bool",
        6121,
    ),
    (
        "ENABLE_GLIN_PROFANITY",
        "maybe",
        6122,
    ),
    (
        "ENABLE_GLIN_PROFANITY",
        "bogus",
        6123,
    ),
    (
        "ENABLE_GLIN_PROFANITY",
        5,
        6124,
    ),
    (
        "ENABLE_GLIN_PROFANITY",
        "not-bool",
        6125,
    ),
    (
        "ENABLE_PROFANITE",
        "maybe",
        6126,
    ),
    (
        "ENABLE_PROFANITE",
        "bogus",
        6127,
    ),
    (
        "ENABLE_PROFANITE",
        5,
        6128,
    ),
    (
        "ENABLE_PROFANITE",
        "not-bool",
        6129,
    ),
    (
        "ENABLE_PROFANITY_FILTER",
        "maybe",
        6130,
    ),
    (
        "ENABLE_PROFANITY_FILTER",
        "bogus",
        6131,
    ),
    (
        "ENABLE_PROFANITY_FILTER",
        5,
        6132,
    ),
    (
        "ENABLE_PROFANITY_FILTER",
        "not-bool",
        6133,
    ),
    (
        "ENABLE_PYPROFANE",
        "maybe",
        6134,
    ),
    (
        "ENABLE_PYPROFANE",
        "bogus",
        6135,
    ),
    (
        "ENABLE_PYPROFANE",
        5,
        6136,
    ),
    (
        "ENABLE_PYPROFANE",
        "not-bool",
        6137,
    ),
    (
        "ENABLE_SAFETEXT",
        "maybe",
        6138,
    ),
    (
        "ENABLE_SAFETEXT",
        "bogus",
        6139,
    ),
    (
        "ENABLE_SAFETEXT",
        5,
        6140,
    ),
    (
        "ENABLE_SAFETEXT",
        "not-bool",
        6141,
    ),
    (
        "ENABLE_SENSITIVE_STOP_WORDS",
        "maybe",
        6142,
    ),
    (
        "ENABLE_SENSITIVE_STOP_WORDS",
        "bogus",
        6143,
    ),
    (
        "ENABLE_SENSITIVE_STOP_WORDS",
        5,
        6144,
    ),
    (
        "ENABLE_SENSITIVE_STOP_WORDS",
        "not-bool",
        6145,
    ),
    (
        "ENABLE_SENSITIVE_WORD_FILTER_CN",
        "maybe",
        6146,
    ),
    (
        "ENABLE_SENSITIVE_WORD_FILTER_CN",
        "bogus",
        6147,
    ),
    (
        "ENABLE_SENSITIVE_WORD_FILTER_CN",
        5,
        6148,
    ),
    (
        "ENABLE_SENSITIVE_WORD_FILTER_CN",
        "not-bool",
        6149,
    ),
    (
        "EXPORT_RETENTION_DAYS",
        -5,
        6150,
    ),
    (
        "EXPORT_RETENTION_DAYS",
        -1,
        6151,
    ),
    (
        "EXPORT_RETENTION_DAYS",
        0,
        6152,
    ),
    (
        "EXPORT_RETENTION_DAYS",
        1000000000,
        6153,
    ),
    (
        "EXPORT_RETENTION_DAYS",
        "not-a-number",
        6154,
    ),
    (
        "FORCE_LLM_ON_SEMANTIC_HIGH",
        "maybe",
        6155,
    ),
    (
        "FORCE_LLM_ON_SEMANTIC_HIGH",
        "bogus",
        6156,
    ),
    (
        "FORCE_LLM_ON_SEMANTIC_HIGH",
        5,
        6157,
    ),
    (
        "FORCE_LLM_ON_SEMANTIC_HIGH",
        "not-bool",
        6158,
    ),
    (
        "FORCE_LLM_ON_USER_RATIO_HIGH",
        "maybe",
        6159,
    ),
    (
        "FORCE_LLM_ON_USER_RATIO_HIGH",
        "bogus",
        6160,
    ),
    (
        "FORCE_LLM_ON_USER_RATIO_HIGH",
        5,
        6161,
    ),
    (
        "FORCE_LLM_ON_USER_RATIO_HIGH",
        "not-bool",
        6162,
    ),
    (
        "FRONTEND_DIST_PATH",
        "",
        6163,
    ),
    (
        "FUZZY_MAX_DISTANCE",
        "",
        6164,
    ),
    (
        "HF_ENDPOINT",
        "",
        6165,
    ),
    (
        "HF_MIRROR",
        "",
        6166,
    ),
    (
        "LLM_RESPONSE_TIMEOUT_SECONDS",
        -5,
        6167,
    ),
    (
        "LLM_RESPONSE_TIMEOUT_SECONDS",
        -1,
        6168,
    ),
    (
        "LLM_RESPONSE_TIMEOUT_SECONDS",
        0,
        6169,
    ),
    (
        "LLM_RESPONSE_TIMEOUT_SECONDS",
        1000000000,
        6170,
    ),
    (
        "LLM_RESPONSE_TIMEOUT_SECONDS",
        "not-a-number",
        6171,
    ),
    (
        "LOG_BACKUP_COUNT",
        -5,
        6172,
    ),
    (
        "LOG_BACKUP_COUNT",
        -1,
        6173,
    ),
    (
        "LOG_BACKUP_COUNT",
        1000000000,
        6174,
    ),
    (
        "LOG_BACKUP_COUNT",
        "not-a-number",
        6175,
    ),
    (
        "LOG_FILE_PATH",
        "",
        6176,
    ),
    (
        "LOG_LEVEL",
        "",
        6177,
    ),
    (
        "LOG_MAX_BYTES",
        -5,
        6178,
    ),
    (
        "LOG_MAX_BYTES",
        -1,
        6179,
    ),
)


class TestInvalidUpdate(BaseTest):
    """Out-of-range or malformed settings values raise ValueError."""

    @pytest.mark.parametrize(
        (
            "key",
            "value",
            "uid",
        ),
        _INVALID_UPDATE_CASES,
    )
    def test_invalid_update(self, engine: Any, key: str, value: object, uid: int) -> None:
        """Out-of-range or malformed settings values raise ValueError."""
        service: SettingsService = engine._settings_service
        service.get(key)
        with pytest.raises(ValueError):
            service.update({key: value})
