"""Phase 2 runtime settings tests (generated).

Catalog metadata, read-only protection, probed valid/invalid matrices
and typed coercion; see tests/tools/phase2_generator.py."""

# multilingual fixtures use non-ASCII on purpose
from __future__ import annotations

from typing import Any

import pytest

from app.settings_service import SettingsService
from tests.base_test import BaseTest

_COERCION_MATRIX_CASES: tuple[tuple[str, str, bool, int], ...] = (
    (
        "SAFE_WORD_ENABLED",
        "no",
        False,
        6439,
    ),
    (
        "SAFE_WORD_ENABLED",
        "no",
        False,
        6440,
    ),
    (
        "SAFE_WORD_ENABLED",
        "no",
        False,
        6441,
    ),
    (
        "SAFE_WORD_ENABLED",
        "no",
        False,
        6442,
    ),
    (
        "SAFE_WORD_ENABLED",
        "no",
        False,
        6443,
    ),
    (
        "SAFE_WORD_ENABLED",
        "no",
        False,
        6444,
    ),
    (
        "SAFE_WORD_ENABLED",
        "no",
        False,
        6445,
    ),
    (
        "SAFE_WORD_ENABLED",
        "no",
        False,
        6446,
    ),
    (
        "SAFE_WORD_ENABLED",
        "no",
        False,
        6447,
    ),
    (
        "SAFE_WORD_ENABLED",
        "no",
        False,
        6448,
    ),
    (
        "USER_WINDOW_DAYS",
        "91",
        91,
        6449,
    ),
    (
        "USER_WINDOW_DAYS",
        "91",
        91,
        6450,
    ),
    (
        "USER_WINDOW_DAYS",
        "91",
        91,
        6451,
    ),
    (
        "USER_WINDOW_DAYS",
        "91",
        91,
        6452,
    ),
    (
        "USER_WINDOW_DAYS",
        "91",
        91,
        6453,
    ),
    (
        "USER_WINDOW_DAYS",
        "91",
        91,
        6454,
    ),
    (
        "USER_WINDOW_DAYS",
        "91",
        91,
        6455,
    ),
    (
        "USER_WINDOW_DAYS",
        "91",
        91,
        6456,
    ),
    (
        "USER_WINDOW_DAYS",
        "91",
        91,
        6457,
    ),
    (
        "USER_WINDOW_DAYS",
        "91",
        91,
        6458,
    ),
    (
        "CACHE_MAX_SIZE",
        "500",
        500,
        6459,
    ),
    (
        "CACHE_MAX_SIZE",
        "500",
        500,
        6460,
    ),
    (
        "CACHE_MAX_SIZE",
        "500",
        500,
        6461,
    ),
    (
        "CACHE_MAX_SIZE",
        "500",
        500,
        6462,
    ),
    (
        "CACHE_MAX_SIZE",
        "500",
        500,
        6463,
    ),
    (
        "CACHE_MAX_SIZE",
        "500",
        500,
        6464,
    ),
    (
        "CACHE_MAX_SIZE",
        "500",
        500,
        6465,
    ),
    (
        "CACHE_MAX_SIZE",
        "500",
        500,
        6466,
    ),
    (
        "CACHE_MAX_SIZE",
        "500",
        500,
        6467,
    ),
    (
        "CACHE_MAX_SIZE",
        "500",
        500,
        6468,
    ),
    (
        "MODEL_MAX_TOKENS",
        "64",
        64,
        6469,
    ),
    (
        "MODEL_MAX_TOKENS",
        "64",
        64,
        6470,
    ),
    (
        "MODEL_MAX_TOKENS",
        "64",
        64,
        6471,
    ),
    (
        "MODEL_MAX_TOKENS",
        "64",
        64,
        6472,
    ),
    (
        "MODEL_MAX_TOKENS",
        "64",
        64,
        6473,
    ),
    (
        "MODEL_MAX_TOKENS",
        "64",
        64,
        6474,
    ),
    (
        "MODEL_MAX_TOKENS",
        "64",
        64,
        6475,
    ),
    (
        "MODEL_MAX_TOKENS",
        "64",
        64,
        6476,
    ),
    (
        "MODEL_MAX_TOKENS",
        "64",
        64,
        6477,
    ),
    (
        "MODEL_MAX_TOKENS",
        "64",
        64,
        6478,
    ),
    (
        "SEMANTIC_SIMILARITY_THRESHOLD",
        "0.9",
        0.9,
        6479,
    ),
    (
        "SEMANTIC_SIMILARITY_THRESHOLD",
        "0.9",
        0.9,
        6480,
    ),
    (
        "SEMANTIC_SIMILARITY_THRESHOLD",
        "0.9",
        0.9,
        6481,
    ),
    (
        "SEMANTIC_SIMILARITY_THRESHOLD",
        "0.9",
        0.9,
        6482,
    ),
    (
        "SEMANTIC_SIMILARITY_THRESHOLD",
        "0.9",
        0.9,
        6483,
    ),
    (
        "SEMANTIC_SIMILARITY_THRESHOLD",
        "0.9",
        0.9,
        6484,
    ),
    (
        "SEMANTIC_SIMILARITY_THRESHOLD",
        "0.9",
        0.9,
        6485,
    ),
    (
        "SEMANTIC_SIMILARITY_THRESHOLD",
        "0.9",
        0.9,
        6486,
    ),
    (
        "SEMANTIC_SIMILARITY_THRESHOLD",
        "0.9",
        0.9,
        6487,
    ),
    (
        "SEMANTIC_SIMILARITY_THRESHOLD",
        "0.9",
        0.9,
        6488,
    ),
)


class TestCoercionMatrix(BaseTest):
    """Typed coercion reproduces the golden value."""

    @pytest.mark.parametrize(
        (
            "key",
            "raw",
            "expected",
            "uid",
        ),
        _COERCION_MATRIX_CASES,
    )
    def test_coercion_matrix(
        self, engine: Any, key: str, raw: str, expected: object, uid: int
    ) -> None:
        """Typed coercion reproduces the golden value."""
        service: SettingsService = engine._settings_service
        service.get(key)
        assert service._coerce(key, raw) == expected
