"""Phase 2 runtime settings tests (generated).

Catalog metadata, read-only protection, probed valid/invalid matrices
and typed coercion; see tests/tools/phase2_generator.py."""

# multilingual fixtures use non-ASCII on purpose
from __future__ import annotations

from typing import Any

import pytest

from app.settings_service import SettingsService
from tests.base_test import BaseTest

_INVALID_UPDATE_CASES: tuple[tuple[str, int, int], ...] = (
    (
        "LOG_MAX_BYTES",
        0,
        6180,
    ),
    (
        "LOG_MAX_BYTES",
        "not-a-number",
        6181,
    ),
    (
        "LOG_MAX_BYTES",
        2.5,
        6182,
    ),
    (
        "LOG_RETENTION_DAYS",
        -5,
        6183,
    ),
    (
        "LOG_RETENTION_DAYS",
        -1,
        6184,
    ),
    (
        "LOG_RETENTION_DAYS",
        0,
        6185,
    ),
    (
        "LOG_RETENTION_DAYS",
        1000000000,
        6186,
    ),
    (
        "LOG_RETENTION_DAYS",
        "not-a-number",
        6187,
    ),
    (
        "MAX_BATCH_SIZE",
        -5,
        6188,
    ),
    (
        "MAX_BATCH_SIZE",
        -1,
        6189,
    ),
    (
        "MAX_BATCH_SIZE",
        0,
        6190,
    ),
    (
        "MAX_BATCH_SIZE",
        1000000000,
        6191,
    ),
    (
        "MAX_BATCH_SIZE",
        "not-a-number",
        6192,
    ),
    (
        "METRICS_ENABLED",
        "",
        6193,
    ),
    (
        "METRICS_PORT",
        "",
        6194,
    ),
    (
        "MODELSCOPE_ENDPOINT",
        "",
        6195,
    ),
    (
        "MODEL_BATCH_SIZE",
        -5,
        6196,
    ),
    (
        "MODEL_BATCH_SIZE",
        -1,
        6197,
    ),
    (
        "MODEL_BATCH_SIZE",
        0,
        6198,
    ),
    (
        "MODEL_BATCH_SIZE",
        1000000000,
        6199,
    ),
    (
        "MODEL_BATCH_SIZE",
        "not-a-number",
        6200,
    ),
    (
        "MODEL_BATCH_SIZE",
        2.5,
        6201,
    ),
    (
        "MODEL_CACHE_TYPE_K",
        "",
        6202,
    ),
    (
        "MODEL_CACHE_TYPE_V",
        "",
        6203,
    ),
    (
        "MODEL_CONTEXT_SIZE",
        -5,
        6204,
    ),
    (
        "MODEL_CONTEXT_SIZE",
        -1,
        6205,
    ),
    (
        "MODEL_CONTEXT_SIZE",
        0,
        6206,
    ),
    (
        "MODEL_CONTEXT_SIZE",
        1000000000,
        6207,
    ),
    (
        "MODEL_CONTEXT_SIZE",
        "not-a-number",
        6208,
    ),
    (
        "MODEL_CONTEXT_SIZE",
        2.5,
        6209,
    ),
    (
        "MODEL_DIR",
        "",
        6210,
    ),
    (
        "MODEL_FALLBACK_REPO",
        "",
        6211,
    ),
    (
        "MODEL_FILENAME",
        "",
        6212,
    ),
    (
        "MODEL_FLASH_ATTN",
        "maybe",
        6213,
    ),
    (
        "MODEL_FLASH_ATTN",
        "bogus",
        6214,
    ),
    (
        "MODEL_FLASH_ATTN",
        5,
        6215,
    ),
    (
        "MODEL_FLASH_ATTN",
        "not-bool",
        6216,
    ),
    (
        "MODEL_IDLE_TIMEOUT_SECONDS",
        -5,
        6217,
    ),
    (
        "MODEL_IDLE_TIMEOUT_SECONDS",
        -1,
        6218,
    ),
    (
        "MODEL_IDLE_TIMEOUT_SECONDS",
        0,
        6219,
    ),
    (
        "MODEL_IDLE_TIMEOUT_SECONDS",
        1000000000,
        6220,
    ),
    (
        "MODEL_IDLE_TIMEOUT_SECONDS",
        "not-a-number",
        6221,
    ),
    (
        "MODEL_IDLE_TIMEOUT_SECONDS",
        2.5,
        6222,
    ),
    (
        "MODEL_MAX_TOKENS",
        -5,
        6223,
    ),
    (
        "MODEL_MAX_TOKENS",
        -1,
        6224,
    ),
    (
        "MODEL_MAX_TOKENS",
        0,
        6225,
    ),
    (
        "MODEL_MAX_TOKENS",
        1000000000,
        6226,
    ),
    (
        "MODEL_MAX_TOKENS",
        "not-a-number",
        6227,
    ),
    (
        "MODEL_MLOCK",
        "maybe",
        6228,
    ),
    (
        "MODEL_MLOCK",
        "bogus",
        6229,
    ),
)


class TestInvalidUpdate(BaseTest):
    """Out-of-range or malformed settings values raise ValueError."""

    @pytest.mark.parametrize(
        (
            "key",
            "value",
            "uid",
        ),
        _INVALID_UPDATE_CASES,
    )
    def test_invalid_update(self, engine: Any, key: str, value: object, uid: int) -> None:
        """Out-of-range or malformed settings values raise ValueError."""
        service: SettingsService = engine._settings_service
        service.get(key)
        with pytest.raises(ValueError):
            service.update({key: value})


_COERCION_MATRIX_CASES: tuple[tuple[str, str, bool, int], ...] = (
    (
        "SAFE_WORD_ENABLED",
        "true",
        True,
        6389,
    ),
    (
        "SAFE_WORD_ENABLED",
        "true",
        True,
        6390,
    ),
    (
        "SAFE_WORD_ENABLED",
        "true",
        True,
        6391,
    ),
    (
        "SAFE_WORD_ENABLED",
        "true",
        True,
        6392,
    ),
    (
        "SAFE_WORD_ENABLED",
        "true",
        True,
        6393,
    ),
    (
        "SAFE_WORD_ENABLED",
        "true",
        True,
        6394,
    ),
    (
        "SAFE_WORD_ENABLED",
        "true",
        True,
        6395,
    ),
    (
        "SAFE_WORD_ENABLED",
        "true",
        True,
        6396,
    ),
    (
        "SAFE_WORD_ENABLED",
        "true",
        True,
        6397,
    ),
    (
        "SAFE_WORD_ENABLED",
        "true",
        True,
        6398,
    ),
    (
        "SAFE_WORD_ENABLED",
        "1",
        True,
        6399,
    ),
    (
        "SAFE_WORD_ENABLED",
        "1",
        True,
        6400,
    ),
    (
        "SAFE_WORD_ENABLED",
        "1",
        True,
        6401,
    ),
    (
        "SAFE_WORD_ENABLED",
        "1",
        True,
        6402,
    ),
    (
        "SAFE_WORD_ENABLED",
        "1",
        True,
        6403,
    ),
    (
        "SAFE_WORD_ENABLED",
        "1",
        True,
        6404,
    ),
    (
        "SAFE_WORD_ENABLED",
        "1",
        True,
        6405,
    ),
    (
        "SAFE_WORD_ENABLED",
        "1",
        True,
        6406,
    ),
    (
        "SAFE_WORD_ENABLED",
        "1",
        True,
        6407,
    ),
    (
        "SAFE_WORD_ENABLED",
        "1",
        True,
        6408,
    ),
    (
        "SAFE_WORD_ENABLED",
        "yes",
        True,
        6409,
    ),
    (
        "SAFE_WORD_ENABLED",
        "yes",
        True,
        6410,
    ),
    (
        "SAFE_WORD_ENABLED",
        "yes",
        True,
        6411,
    ),
    (
        "SAFE_WORD_ENABLED",
        "yes",
        True,
        6412,
    ),
    (
        "SAFE_WORD_ENABLED",
        "yes",
        True,
        6413,
    ),
    (
        "SAFE_WORD_ENABLED",
        "yes",
        True,
        6414,
    ),
    (
        "SAFE_WORD_ENABLED",
        "yes",
        True,
        6415,
    ),
    (
        "SAFE_WORD_ENABLED",
        "yes",
        True,
        6416,
    ),
    (
        "SAFE_WORD_ENABLED",
        "yes",
        True,
        6417,
    ),
    (
        "SAFE_WORD_ENABLED",
        "yes",
        True,
        6418,
    ),
    (
        "SAFE_WORD_ENABLED",
        "false",
        False,
        6419,
    ),
    (
        "SAFE_WORD_ENABLED",
        "false",
        False,
        6420,
    ),
    (
        "SAFE_WORD_ENABLED",
        "false",
        False,
        6421,
    ),
    (
        "SAFE_WORD_ENABLED",
        "false",
        False,
        6422,
    ),
    (
        "SAFE_WORD_ENABLED",
        "false",
        False,
        6423,
    ),
    (
        "SAFE_WORD_ENABLED",
        "false",
        False,
        6424,
    ),
    (
        "SAFE_WORD_ENABLED",
        "false",
        False,
        6425,
    ),
    (
        "SAFE_WORD_ENABLED",
        "false",
        False,
        6426,
    ),
    (
        "SAFE_WORD_ENABLED",
        "false",
        False,
        6427,
    ),
    (
        "SAFE_WORD_ENABLED",
        "false",
        False,
        6428,
    ),
    (
        "SAFE_WORD_ENABLED",
        "0",
        False,
        6429,
    ),
    (
        "SAFE_WORD_ENABLED",
        "0",
        False,
        6430,
    ),
    (
        "SAFE_WORD_ENABLED",
        "0",
        False,
        6431,
    ),
    (
        "SAFE_WORD_ENABLED",
        "0",
        False,
        6432,
    ),
    (
        "SAFE_WORD_ENABLED",
        "0",
        False,
        6433,
    ),
    (
        "SAFE_WORD_ENABLED",
        "0",
        False,
        6434,
    ),
    (
        "SAFE_WORD_ENABLED",
        "0",
        False,
        6435,
    ),
    (
        "SAFE_WORD_ENABLED",
        "0",
        False,
        6436,
    ),
    (
        "SAFE_WORD_ENABLED",
        "0",
        False,
        6437,
    ),
    (
        "SAFE_WORD_ENABLED",
        "0",
        False,
        6438,
    ),
)


class TestCoercionMatrix(BaseTest):
    """Typed coercion reproduces the golden value."""

    @pytest.mark.parametrize(
        (
            "key",
            "raw",
            "expected",
            "uid",
        ),
        _COERCION_MATRIX_CASES,
    )
    def test_coercion_matrix(
        self, engine: Any, key: str, raw: str, expected: object, uid: int
    ) -> None:
        """Typed coercion reproduces the golden value."""
        service: SettingsService = engine._settings_service
        service.get(key)
        assert service._coerce(key, raw) == expected
